apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
      tier: backend
  template:
    metadata:
      labels:
        app: mariadb
        tier: backend
    spec:
      volumes:
        - name: volumen-mariadb
          persistentVolumeClaim:
            claimName: pvc-mariadb
      containers:
        - name: contenedor-mariadb
          image: mariadb
          ports:
            - name: mariadb-server
              containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: volumen-mariadb
          env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: MARIADB_ROOT_PASSWORD
          - name: MARIADB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: database
                key: MARIADB_DATABASE
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: MARIADB_USER
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: MARIADB_PASSWORD
