apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: default
type: Opaque
stringData:
    DB_PASSWORD: lara
    DB_USER: lara
    MARIADB_PASSWORD: lara
    MARIADB_ROOT_PASSWORD: root
    MARIADB_USER: lara
